'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class PrintReports
    
    '''<summary>
    '''lblErrorMsg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblErrorMsg As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''btnPrintReportAgentSales control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnPrintReportAgentSales As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnPrintReportAgentTopUp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnPrintReportAgentTopUp As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnPrintReportAgentSalesAll control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnPrintReportAgentSalesAll As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnPrintReportAgentTopUpAll control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnPrintReportAgentTopUpAll As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnSimCardBalance control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSimCardBalance As Global.System.Web.UI.WebControls.Button
End Class
