'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class UpkeepTxAdd
    
    '''<summary>
    '''txtOpeningDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtOpeningDate As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtStarhub_No control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtStarhub_No As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtStarhubO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtStarhubO As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtM1_No control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtM1_No As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtM1O control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtM1O As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtM5O control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtM5O As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtM18O control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtM18O As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtM28O control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtM28O As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtSingtel_No control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSingtel_No As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtSingtel5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSingtel5 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtSingtel10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSingtel10 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtSingtel20 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSingtel20 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtSingtel50 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSingtel50 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtSingtel16 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSingtel16 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtSingtel15 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSingtel15 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtSingtel28 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSingtel28 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtSingtel300 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSingtel300 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtSingtel180 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSingtel180 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtSingtel888 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSingtel888 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtSingtel102 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSingtel102 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtSingtel1015 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSingtel1015 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtSingtel118 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSingtel118 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtSingtel1315 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSingtel1315 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtSingtel119 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSingtel119 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtSingtel2504 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSingtel2504 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtSingtel120 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSingtel120 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''btnSubmit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSubmit As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''lblErrorMsg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblErrorMsg As Global.System.Web.UI.WebControls.Label
End Class
