'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Upkeep
    
    '''<summary>
    '''TextBox1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBox1 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtOpeningDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtOpeningDate As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtStarhubO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtStarhubO As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtM1O control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtM1O As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtM5O control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtM5O As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtM18O control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtM18O As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtM28O control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtM28O As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtSingtel5o control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSingtel5o As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtSingtel8o control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSingtel8o As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtSingtel10o control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSingtel10o As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtSingtel15o control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSingtel15o As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtSingtel18o control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSingtel18o As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtSingtel20o control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSingtel20o As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtSingtel22o control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSingtel22o As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtSingtel28o control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSingtel28o As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtSingtel30o control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSingtel30o As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtSingtel50o control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSingtel50o As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''Label1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label1 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtCurrentDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCurrentDate As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtStarhubc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtStarhubc As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtM1c control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtM1c As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtM5c control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtM5c As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtM18c control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtM18c As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtM28c control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtM28c As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtSingtel5c control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSingtel5c As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtSingtel8c control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSingtel8c As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtSingtel10c control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSingtel10c As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtSingtel15c control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSingtel15c As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtSingtel18c control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSingtel18c As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtSingtel20c control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSingtel20c As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtSingtel22c control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSingtel22c As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtSingtel28c control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSingtel28c As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtSingtel30c control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSingtel30c As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtSingtel50c control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSingtel50c As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblstatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblstatus As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''btnSubmit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSubmit As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnClose control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnClose As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''lblErrorMsg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblErrorMsg As Global.System.Web.UI.WebControls.Label
End Class
